# docker-compose.yml
# Orchestrates backend, Postgres, ChromaDB, and frontend services for HomeAssistant Voice LLM project
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ha_voice_backend
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
      - ./.env:/app/.env
    environment:
      - ENV=development
      - DEBUG=true
    depends_on:
      - postgres
      - chromadb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ha_voice_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/app/shared
      - ./.env:/app/.env
    environment:
      - ENV=development
      - DEBUG=true
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: ha_voice_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: ha_voice_chromadb
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  chroma_data:
    driver: local

# See each service's README for further setup and configuration details.
