# docker-compose.yml
# Orchestrates backend, Postgres, ChromaDB, and frontend services for HomeAssistant Voice LLM project
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        DOCKER_DEFAULT_PLATFORM: linux/arm64
    container_name: ha_backend
    env_file:
      - ./shared/config/.env
    depends_on:
      - db
      - chromadb
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/home_assistant
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: ha_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: ha_chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        DOCKER_DEFAULT_PLATFORM: linux/arm64
    container_name: ha_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  voice:
    build:
      context: ./voice
      args:
        DOCKER_DEFAULT_PLATFORM: linux/arm64
    container_name: ha_voice
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./voice:/app
      - voice_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  chromadb_data:
    driver: local
  backend_data:
    driver: local
  voice_data:
    driver: local

# See each service's README for further setup and configuration details.
